name: record_me
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
 sdk: '>=2.7.0 <3.0.0'

dependencies:
 flutter:
  sdk: flutter

 cupertino_icons: ^0.1.3
 font_awesome_flutter: '>= 4.7.0'
 shared_preferences: ^0.5.7+3
 animate_do: ^1.7.2
 provider: ^4.1.3
 fluttertoast: ^4.0.0
 flutter_colorpicker: ^0.3.4
 flutter_staggered_grid_view: ^0.3.0

dev_dependencies:
 flutter_launcher_icons: ^0.7.5
 flutter_test:
  sdk: flutter

# The following section is specific to Flutter.
flutter:
 uses-material-design: true
 # To add assets to your application, add an assets section, like this:
 # assets:
 #   - images/a_dot_burr.jpeg
